"""create all tables

Revision ID: 58c25df1e1ce
Revises: 
Create Date: 2026-05-31 18:25:47.757120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '58c25df1e1ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('target_role', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('cv_filename', sa.String(length=255), nullable=True),
    sa.Column('cv_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True, comment="JSON array: ['angular', 'python', 'typescript']"),
    sa.Column('target_roles', sa.Text(), nullable=True, comment="JSON array: ['Desenvolvedor Frontend', 'Full Stack']"),
    sa.Column('preferred_locations', sa.Text(), nullable=True, comment="JSON array: ['São Paulo', 'Remoto']"),
    sa.Column('scan_interval_hours', sa.Integer(), nullable=False),
    sa.Column('auto_apply', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('application_url', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('next_send_at', sa.DateTime(), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fixed_companies_is_active', 'fixed_companies', ['is_active'], unique=False)
    op.create_index('ix_fixed_companies_next_send_at', 'fixed_companies', ['next_send_at'], unique=False)
    op.create_index('ix_fixed_companies_status', 'fixed_companies', ['status'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('salary_range', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('found_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_found_at', 'jobs', ['found_at'], unique=False)
    op.create_index('ix_jobs_platform', 'jobs', ['platform'], unique=False)
    op.create_index('ix_jobs_platform_status', 'jobs', ['platform', 'status'], unique=False)
    op.create_index('ix_jobs_score', 'jobs', ['score'], unique=False)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('screenshot_path', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('fixed_company_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fixed_company_id'], ['fixed_companies.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_applications_is_recurring', 'applications', ['is_recurring'], unique=False)
    op.create_index('ix_applications_job_id', 'applications', ['job_id'], unique=False)
    op.create_index('ix_applications_sent_at', 'applications', ['sent_at'], unique=False)
    op.create_index('ix_applications_status', 'applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_applications_status', table_name='applications')
    op.drop_index('ix_applications_sent_at', table_name='applications')
    op.drop_index('ix_applications_job_id', table_name='applications')
    op.drop_index('ix_applications_is_recurring', table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_score', table_name='jobs')
    op.drop_index('ix_jobs_platform_status', table_name='jobs')
    op.drop_index('ix_jobs_platform', table_name='jobs')
    op.drop_index('ix_jobs_found_at', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_fixed_companies_status', table_name='fixed_companies')
    op.drop_index('ix_fixed_companies_next_send_at', table_name='fixed_companies')
    op.drop_index('ix_fixed_companies_is_active', table_name='fixed_companies')
    op.drop_table('fixed_companies')
    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###
